### ISSUE TITLE
Update peers.sh to detect if instance is part of a spot fleet

### ISSUE THREAD

**Issue by randywallace** [weaveworks/integrations#1]
Spot Fleets are a very new feature in AWS that, from a cost-savings perspective, could be very beneficial when used in conjunction with ECS, especially for temporary and potentially large environments, i.e. QA and Testing.

The peers.sh script looks like it could easily be updated to failover to detecting if an instance is part of a spot fleet via http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-spot-fleet-instances.html, which could then grab the list of peer ips since that command returns the instance ids.

I plan on beginning testing spot fleets shortly, and will update the script in a PR, if you guys don't want to try your hand at it first.

**Comment by 2opremio** [comment]
Thanks @randywallace . I will look into if time allows but we of course welcome pull requests!

**Comment by randywallace** [comment]
I updated the peers.sh on a topic branch.

It is some much heavier bash, and makes use of the JMESPath in aws-cli instead of `jq`.

https://github.com/randywallace/integrations/blob/topic-spot-fleet/aws/ecs/packer/to-upload/peers.sh

I haven't submitted a PR, because honestly I haven't started a Spot Fleet with more than one instance yet, but I know it works on autoscaling.

**Comment by randywallace** [comment]
I also added a meta data service loop, b/c in my experience it really does return zilch once on a while on basic stuff like the instance-id with a 200 http status.

https://github.com/randywallace/integrations/blob/topic-spot-fleet/aws/ecs/packer/to-upload/peers.sh#L28

**Comment by randywallace** [comment]
Actually, I went crazy and added support for finding instances by tag as well.  If the instance has the tag 'WEAVE_ECS' it will find all the other instances with that tag, and matching value (i.e. WEAVE_ECS=prod) and return the IP's for those.

So the instance finding goes:
1) try tags first
2) then see if its in an autoscaling group
3) then try to find peers in a spot fleet

It should be resilient enough to, even if an instance does have a WEAVE_ECS tag, try step 2 and so on if it can't find any other matching instances.

**Comment by 2opremio** [comment]
@randywallace Nice! Thanks. Would you mind creating a PR? 

I don't think we should have a default tagname and just make it configurable, but we can discuss it in the PR.

**Comment by randywallace** [comment]
I agree actually, but since this gets packed into an AMI, I don't know how to set that for the user, without perhaps using user-data (but then again, we don't know what people may be doing with the user data!).

I fully intend to create a PR, but would prefer before doing that to actually confirm that my spot fleet code works (I haven't yet actually started one in AWS with more than one instance in the fleet).  I will likely do this tomorrow.

**Comment by 2opremio** [comment]
Yep, my idea is to use User Data.

Sure, there is no urgency, create the PR once you have tested it.
