### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by mnwalker** [weaveworks/integrations#104]
https://www.weave.works/guides/service-discovery-and-load-balancing-with-weave-on-amazon-ecs-2/
In the manual setup, it all works but wont connect to cloud.

`echo "SCOPE_AAS_PROBE_TOKEN=XXXX" >> ./user-data.sh`
Should be
`echo "echo SERVICE_TOKEN=XXXX >> /etc/weave/scope.config" >> ./user-data.sh`

**Comment by 2opremio** [comment]
Good catch! Moved to https://github.com/weaveworks/guides/issues/213
