### ISSUE TITLE
AWS weave cloud can not find my ecs instance

### ISSUE THREAD

**Issue by FYYKX** [weaveworks/integrations#106]
add file scope.config to /etc/weave/scope.config
with SCOPE_AAS_PROBE_TOKEN=mytoken

root      2542  0.0  0.0  11864  2856 ?        Ss   02:44   0:05 /bin/bash /etc/weave/run.sh scope
ec2-user 16990  0.0  0.0 110460  2140 pts/0    S+   08:33   0:00 grep --color=auto scope
root     27148  7.7  2.2 326408 90200 ?        Sl   08:08   1:56 scope-app --mode app --probe.docker=true
root     27149  5.7  1.3 259716 54804 ?        Sl   08:08   1:27 scope-probe --mode probe --probe.docker=true

AMI ami-10885073

**Comment by 2opremio** [comment]
It's SERVICE_TOKEN and not SCOPE_AAS_PROBE_TOKEN . Sorry about that. PR coming up

**Comment by FYYKX** [comment]
Thx a lot! it works

**Comment by 2opremio** [comment]
No problem, sorry for the confusion it caused.
