### ISSUE TITLE
Cloud formation: the WeaveScope output shouldn't be loadbalanced

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/integrations#115]
The WeaveScope output goes through an ELB:

<img width="1535" alt="screen shot 2016-11-17 at 12 42 47" src="https://cloud.githubusercontent.com/assets/2362916/20388076/794fc438-acc3-11e6-9a50-a5472b2240cb.png">

This is wrong since it leads to a split brain in the apps, affecting things like terminal spawning:

See: https://github.com/weaveworks/scope/issues/2016#issuecomment-261226026

**Comment by errordeveloper** [comment]
Perhaps we could just run one app behind the ELB?

**Comment by 2opremio** [comment]
Why use an ELB if there's going to be a single app? I would suggest simply enabling public DNS for the instances and picking one of them for the WeaveScope output.

**Comment by errordeveloper** [comment]
> Why use an ELB if there's going to be a single app?

Good question! The reason for this is that there is no other easy way to display a URL in outputs section of CloudFormation stack status page.

**Comment by 2opremio** [comment]
Then fine as long as it works and it's commented (assuming you can comment in CF templates)

**Comment by errordeveloper** [comment]
> assuming you can comment in CF templates

No, it's JSON.

**Comment by lukemarsden** [comment]
Can we just tell people to use Weave Cloud for their Scope UI?

**Comment by errordeveloper** [comment]
Luke, yes, I've asked the same question earlier. Fons believes that the
extra step needed right now doesn't do well for UX, but we can do that once
we have new getting started page, we can just link to CloudFormation with a
toke in the URL.

**Comment by errordeveloper** [comment]
I would prefer to fix this with sticky sessions. Fons, you have mentioned
that you foresee some problems with that - could you please outline those?

**Comment by 2opremio** [comment]
> you foresee some problems with that - could you please outline those?

The stateful nature of sticky sessions brings problems in my experience. But, give it a spin and let's see what happens.

**Comment by errordeveloper** [comment]
Turns out classic ELB only supports stick session for HTTP listeners, and Scope listener has to be a TCP one, due to the use of WebSockets. I haven't looked into ELBv2 yet, and I'd rather encourage the use Weave Cloud, which is also more secure as standalone mode doesn't even do TLS.
