### ISSUE TITLE
AMI 2015-12-17.b not available in eu-central-1 

### ISSUE THREAD

**Issue by fabfuel** [weaveworks/integrations#54]
The current version `2015-12-17.b` is not available in region `eu-central-1` yet and the README (https://github.com/weaveworks/integrations/blob/master/aws/ecs/README.md) points to the wrong AMI id (duplicate of `eu-west-1`).

**Comment by 2opremio** [comment]
Thanks for reporting this Fabian. I am on vacation until Jan 7, but I will
look into this as soon as I am back.

**Comment by fabfuel** [comment]
Great, thanks! Enjoy your vacations
