### ISSUE TITLE
Adopt the CloudFormation template

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/integrations#59]
Once #58 is done, adopt the CloudFormation as the default way of doing things.

We can probably get rid of vendor AMIs and leverage [`AWS::CloudFormation::Init`](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html) for provisioning the instances. The shell scripts script can also leverage [CloudFormation via the CLI](http://docs.aws.amazon.com/cli/latest/reference/cloudformation/index.html), potentially keeping the guide UX the same. We can implement #24 by means of parametrised stack update.

**Comment by errordeveloper** [comment]
There seems to be an issue with how stack updates work, turns out that changing a parameter (namely `WeaveNetVersion`) doesn't qualify for a stack update... Should investigate more.

**Comment by 2opremio** [comment]
What do you mean by _default way of doing things._ ? In the ECS guide?

Then this ticket should be moved there.
