### ISSUE TITLE
CloudFormation button

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/integrations#72]
We should add "Deploy stack" button
```
https://console.aws.amazon.com/cloudformation/home#/stacks/new?templateURL=https:%2F%2Fs3.amazonaws.com%2Fweaveworks-cfn-public%2Fintegrations%2Fecs-baseline.json
```

MBOI: https://blogs.aws.amazon.com/application-management/post/Tx2YSVJV4VMPBHI/Construct-Your-Own-Launch-Stack-URL

**Comment by errordeveloper** [comment]
ping #59

**Comment by 2opremio** [comment]
I think this ticket belongs to guides/website/wherever-we want-to-use-the-button.
