### ISSUE TITLE
ETA for new AMI with Scope 0.13

### ISSUE THREAD

**Issue by bryanvaz** [weaveworks/integrations#74]
We were wondering what the ETA was for rolling a new AMI with Weave updates (i.e. Scope 0.13). Because the latest AMIs have 0.11. the scope process is chewing up alot of CPU on our AWS instances.

**Comment by 2opremio** [comment]
Hi @bryanvaz . I am planning to release new AMIs  tomorrow (we first want to upgrade scope.weave.works ). Is that good enough or is there more urgency?

Out of curiosity, what's the current CPU consumption/load in the probes/apps?  How many hosts, containers per host are  your running? Are you using Standalone mode or Service mode? (I know, a lot of questions but your answers could be very helpful)

**Comment by bryanvaz** [comment]
That's totally fine. We were just wondering if we should roll our own or wait for you to build it.

On an m3.medium, the scope process uses about 15-20% CPU with no containers. Adding two containers (under load) on the same host, that do minimal talking to each other, causes scope to rest at 20%. 

On a t2.small scope uses about 7-10% so, it is partially caused by the slower CPU on the m3 instances.

Test ENV:
Scope Standalone
ami-03c40860
ap-southeast-1
No probes
m3.medium
1 host
2 containers
~ 43 requests per minute
~ 60 external DB transactions/requests

**Comment by 2opremio** [comment]
Thanks for the info. The update of the AMI slipped until next week because I want to fix #1 in order to get you forward with #73 . Can you confirm that tag-based peer-identification will be good-enough for you?

**Comment by bryanvaz** [comment]
@2opremio tags will work fine for us.

**Comment by 2opremio** [comment]
I have just released a new AMI with Scope 0.13.1. Closing.
