### ISSUE TITLE
Ship Weave Flux with ECS AMIs

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/integrations#84]
Right now only Weave Net and Scope are included.

**Comment by kingdonb** [comment]
Can you use Flux and ECS together?  I found this stub for an article and nothing else about it: https://tzrlk.aetheric.co.nz/devops/2017/12/12/setting-up-weaveworks-flux-on-amazon-ecs.html

I'm evaluating Weave Cloud as a possible solution, it might be an easier sell if it doesn't need to come bundled with Kubernetes, but without Flux it's gonna be a no from me.

(And Flux operates on Kubernetes yaml manifests from what I read so far, so this whole question might be a non-starter.  Then again there's the helm operator...)

**Comment by 2opremio** [comment]
Yes, this refers to the previous incarnation of flux (renamed to flux classic) and it doesn't apply anymore.

**Comment by 2opremio** [comment]
To be clear, flux could potentially support ECS apart from Kubernetes, but that's not the case now.

**Comment by kingdonb** [comment]
OK, I'll try out https://www.weave.works/docs/cloud/latest/install/ecs-no-kubernetes/ and see.  I think the most value of Weave tools comes from Flux for me; it's clear that Kubernetes is the target platform.

Thanks!
