### ISSUE TITLE
Dedup CNF with a framework

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/integrations#86]
There is a number of helpers that make CFN templates reusable, we must start using those as the number of template forks grew for different demos. Generating these templates would also make bumping versions a lot easier. Some have better validation built-in, so we can improve how this stuff is tested.

**Comment by errordeveloper** [comment]
e.g https://github.com/tuxpiper/cloudcast and https://github.com/chrisfjones/coffin

**Comment by errordeveloper** [comment]
CFN provides native re-usability through nested stacks, but that is not useful for us, as we want to publish a single template that user can deploy in their own infra.

**Comment by errordeveloper** [comment]
It is quite open-ended, we can discuss nested stack also, I haven't looked very closely, and my comment above is based on initial observations.

**Comment by errordeveloper** [comment]
There is also https://github.com/cloudtools/troposphere, which ClusterHQ [uses](https://github.com/ClusterHQ/flocker/blob/master/admin/installer/cloudformation.py).

**Comment by errordeveloper** [comment]
Generating these templates would also make bumping versions a lot easier.

**Comment by 2opremio** [comment]
> https://github.com/cloudtools/troposphere

It seems like a best option although it's maybe overkill for only three scripts. Isn't there a way to factor templates using a DSL embedded in json, without needing to code in python (or any other programming language)?

Maybe even golang templates would be enough.

**Comment by errordeveloper** [comment]
I couldn't find a nice way of doing things in JSON DSL, it does allow you do some stuff... One smart feature it has is Lambda integration, so you can provide custom functions that do almost anything, e.g. lookup AMI, lookup ECS task and service definitions.

We could probably do something without doing anything too clever with Lambda. Right now most templates have a boolean condition whether to deploy ECS tasks and service... We could probably add different demo apps and provide a drop-down menu for the app user may wish, but all of this is a lot of JSON and UX is pretty poor. Generating JSON and providing a different UX on top of that seems much better, which is another reason I've started this discussion.

**Comment by errordeveloper** [comment]
- `cloudformation-identiorca.json` the Identiorca app that Adrian built, it's quite nice for demostrating the load-balancing functionality
- `cloudformation-larger-app.json` a somewhat larger app, which doesn't really have a functional web frontend that user can look at, but it does render nicelly in Scope
- `cloudformation.json` simple Redis+Flask hit-counter, as seen in the Docker Compose tutorial

**Comment by errordeveloper** [comment]
https://github.com/weaveworks/integrations/issues/99

**Comment by errordeveloper** [comment]
# An example of where it becomes really painful

We have [an ELB](https://github.com/weaveworks/integrations/blob/373137c9cdb7622eac567a63db4f0befb2a29d91/aws/ecs/cloudformation-identiorca.json#L735) in front of the all instances configured to forward ports 80 (for the example app) and port 4040 for Scope app. 

We have two user parameters from which CloudFormation conditionals are created:
- [`DoDeployExampleApp `](https://github.com/weaveworks/integrations/blob/373137c9cdb7622eac567a63db4f0befb2a29d91/aws/ecs/cloudformation-identiorca.json#L150)
- [`UseScopeService `](https://github.com/weaveworks/integrations/blob/373137c9cdb7622eac567a63db4f0befb2a29d91/aws/ecs/cloudformation-identiorca.json#L158)

When user sets either of these to non-default value, the ELB is broken. For example, when Scope app is missing and Weave Cloud is used, it treats port 4040 as unhealthy, and marks all instances as `OutOfService`. Same happens the other way around, if user chose to no deploy the example app.

We need to somehow configure the ELB to respect both of the conditionals. May be we can have separate ELBs, and disable those based on the aforementioned conditionals...

However, the ASG also requires us to register references to ELBs under [`LoadBalancerNames`](https://github.com/weaveworks/integrations/blob/373137c9cdb7622eac567a63db4f0befb2a29d91/aws/ecs/cloudformation-identiorca.json#L710-L713). This gets more painful, because I do not believe we can pass an empty list or list of nils... It sounds like we have to create two AGSs under those conditions, causing even more duplication within the template - one ASG would have `LoadBalancerNames` set when there is at least one ELB, and another one without `LoadBalancerNames` when there are none, we would have select those...

Ok, so one of the problems is that it's hard to tell if empty lists are okay or whether nils are or whatever, some bugs pass validation and only surface 10 minutes through stack creation process. Docs aren't quite helpful regarding such kind of cases.

My second point is that it's not worse spending so much time even detailing this problem, while there are known tools that solve various kinds of problems, proving that macros aren't enough.

Additionally, the macros language is very very clunky and it's all JSON. It's hard to figure what to do each time you have to use yet another macro. It's just not intuitive, and implementing anything takes long, and it's also hard to tell what's going to work and what's not.

**Comment by errordeveloper** [comment]
Ok, after looking through the docs for a while, it turns out I can use `{"Ref" : "AWS::NoValue"}`...
