### ISSUE TITLE
CFN errors ocasionally

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/integrations#87]
Seems like we might need to implement implicit success report, using [`cfn-signal`](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-signal.html).

**Comment by errordeveloper** [comment]
xref https://github.com/microservices-demo/microservices-demo/issues/413#issuecomment-260921298

**Comment by 2opremio** [comment]
For me it's systematic unless I use large instances (`m4.xlarge`)

**Comment by errordeveloper** [comment]
xref https://github.com/weaveworks/integrations/issues/116
