### ISSUE TITLE
Dicuss what CloudFormation templates we have right now and which can be pruned

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/integrations#99]
Just for the record, here is what we currently have. Let's discuss whether we need all these forked templates.
- `cloudformation-identiorca.json` the Identiorca app that @amouat built, it's quite nice for demostrating the load-balancing functionality;  this template also has less options for the user to pick
- `cloudformation-larger-app.json` a somewhat larger app, which doesn't really have a functional web frontend that user can look at, but it does render nicelly in Scope
- `cloudformation.json` simple Redis+Flask hit-counter, as seen in the Docker Compose tutorial

**Comment by 2opremio** [comment]
What's the issue? Considering to simplify the templates? The title should be actionable (which isn't right now).

**Comment by errordeveloper** [comment]
> Considering to simplify the templates?

Yes. Reduce duplication etc.

> Considering to simplify the templates?

Good call, I've changed the title.
